export const EVENTBRITE_API_KEY = 'QWZWM6CDIXJRAOHDGJ7Y';

//DIRECTIONS KEY
export const GOOGLEMAPS_API_KEY = 'AIzaSyC4sITGIQEKBi1ejAZxazvwZlrk1pi7OeA';

//GOOGLE PLACES KEY
export const PLACES_KEY = 'AIzaSyDyhX_OZQhbhACB6jwxC-nZLWz0RsTQ6wQ';

//GEOCODE API KEY
export const GEO_CODE_API_KEY = 'AIzaSyB8IxbziuW2kanvpvQ12sCUfq1JluwTNgE';
